volumes:
    db_data: {}
    data: {}
    libreNMS-data: {}

networks:
  innet:
    external:
      name: back-tier
  outnet:
    external:
      name: front-tier
      
services:
  db: 
    image: mariadb:lts
    container_name: librenms_db
    command:
      - "mysqld"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "db_data:/var/lib/mysql"
    networks:
      - innet
    env_file:
      - stack.env
    environment:
      - "TZ=${TZ}"
      - "MARIADB_RANDOM_ROOT_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    restart: always

  redis:
    image: redis:7.2-alpine
    container_name: librenms_redis
    networks:
      - innet
    env_file:
      - stack.env
    environment:
      - "TZ=${TZ}"
    restart: always

  main:
    image: librenms/librenms:latest
    networks:
      - innet
      - outnet
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - 8001:8000
    depends_on:
      - db
      - redis
    volumes:
      - "libreNMS-data:/data"
    env_file:
      - stack.env
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
    restart: always

  dispatcher:
    image: librenms/librenms:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - main
      - redis
    volumes:
      - "libreNMS-data:/data"
    env_file:
      - stack.env
    networks:
      - innet
      - outnet
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "DISPATCHER_NODE_ID=dispatcher1"
      - "SIDECAR_DISPATCHER=1"
    restart: always
