volumes:
    db_data: {}
    data: {}
    libreNMS-data: {}

networks:
  innet:
    external:
      name: back-tier
  outnet:
    external:
      name: front-tier
      
services:
  db: 
    image: mariadb:lts
    volumes:
      - "db_data:/var/lib/mysql"
    networks:
      - innet
    environment:
      - "TZ=${TZ}"
      - "MARIADB_RANDOM_ROOT_PASSWORD=yes"
      - "MYSQL_DATABASE=${DB_DB}"
      - "MYSQL_USER=${DB_USR}"
      - "MYSQL_PASSWORD=${DB_PWD}"
    restart: always

  redis:
    image: redis:alpine
    networks:
      - innet
    env_file:
      - stack.env
    environment:
      - "TZ=${TZ}"
    restart: always

  main:
    image: librenms/librenms:latest
    networks:
      - innet
      - outnet
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - 8001:8000
    depends_on:
      - db
      - redis
    volumes:
      - "libreNMS-data:/data"
    env_file:
      - ./libreNMS/librenms.env
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${DB_DB}"
      - "DB_USER=${DB_USR}"
      - "DB_PASSWORD=${DB_USR}"
      - "DB_TIMEOUT=60"
    restart: always

  dispatcher:
    image: librenms/librenms:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - main
      - redis
    volumes:
      - "libreNMS-data:/data"
    env_file:
      - ./libreNMS/librenms.env
    networks:
      - innet
      - outnet
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${DB_DB}"
      - "DB_USER=${DB_USR}"
      - "DB_PASSWORD=${DB_PWD}"
      - "DB_TIMEOUT=60"
      - "DISPATCHER_NODE_ID=dispatcher1"
      - "SIDECAR_DISPATCHER=1"
    restart: always
