volumes:
    db_data: {}
    data: {}
    libreNMS-data: {}

networks:
  innet:
    external:
      name: back-tier
  outnet:
    external:
      name: front-tier
      
services:
  db: 
    image: mariadb:10
    volumes:
      - "db_data:/var/lib/mysql"
    networks:
      - innet
    environment:
      - "TZ=${TZ}"
      - "MARIADB_RANDOM_ROOT_PASSWORD=no"
      - "MYSQL_DATABASE=${DB_DB}"
      - "MYSQL_USER=${DB_USR}"
      - "MYSQL_PASSWORD=${DB_PWD}"
    restart: always

  redis:
    image: redis:alpine
    networks:
      - innet
    env_file:
      - stack.env
    environment:
      - "TZ=${TZ}"
    restart: always

  main:
    image: librenms/librenms:latest
    networks:
      - innet
      - outnet
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - 8001:8000
    depends_on:
      - db
      - redis
    volumes:
      - "libreNMS-data:/data"
    #env_file:
    #  - ./libreNMS/librenms.env
    #  - ./libreNMS/.env
    environment:
      - "TZ=${TZ}"
      - "DB_HOST=db"
      - "DB_NAME=${DB_DB}"
      - "DB_USER=${DB_USR}"
      - "DB_PASSWORD=${DB_PWD}"
      - "DB_TIMEOUT=60"
    restart: always
