# global config
global:

  # 拉取目標的默認時間間隔
  # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_interval:     3s 

  # 執行規則的時間間隔
  # Evaluate rules every 3 seconds. The default is every 1 minute.
  evaluation_interval: 3s 

  # scrape_timeout is set to the global default (10s)拉取一個目標原子的時間.
  # external_labels：額外的屬性，會添加到拉取的數據並存到數據庫中

# Alertmanager configuration 
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

# 根據alert.yml 的規則，並依造evaluation_interval的時間做拉取
rule_files:
  - "alert.yml"

# 抓取資料的目標
scrape_configs:
  # 任務名稱
  - job_name: 'prometheus'
    # 覆蓋global 時間，這邊可以自行指定該服務要多久抓一次
    scrape_interval: 3s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    scrape_interval: 3s
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'relay-2-IMAP'
    scrape_interval: 60s
    static_configs:
      - targets: ['relay2.ce.ncu.edu.tw:143']
      
  - job_name: 'relay-2-POP3'
    scrape_interval: 60s
    static_configs:
      - targets: ['relay2.ce.ncu.edu.tw:110']
