global:
  smtp_smarthost: 'smtp.gmail.com:587'
  # 從哪裡寄信
  smtp_from: '自己的@gmail.com'
  # 哪個帳號管裡
  smtp_auth_username: '自己的@gmail.com'
  # 密碼
  smtp_auth_password: '應用程式的密碼，不是你自己的'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 15s ## 將緩衝警報15S 等待同一組其他條件 要是符合就一起寄
  group_interval: 3s ## 設置控制在發送同一組的進一步通知之前等待多長時間，並且時間間隔從發送的最後一個通知開始計算。
  # repeat_interval: 10m ## 十分鐘寄一次
  receiver: live-monitoring

receivers:
- name: 'live-monitoring'
  # 收件人
  email_configs:
  - to: '收件人@gmail.com'
